spring:
  application:
    name: redis-reactive-cache
  main:
    web-application-type: reactive
  profiles:
    active: lib
---
spring:
  config:
    activate:
      on-profile: lib
  data:
    redis:
      host: "localhost"
      port: 6379
      database:
      username:
      password:
      client-name: ${spring.application.name}
      client-type: lettuce #provide reactive connection
      date_format: "dd-MM-yyyy"
      time_format: "HH:mm:ss"